languageCode = "DE-de"
title = "Schreinerei Ammann"
[params]
    description = "Aus Liebe zum Holz – Ihr Schreinermeisterbetrieb in Dirlewang/Unterallgäu"
baseURL = "https://schreinerei-ammann.de/"
canonifyurls = false